import 'package:flutter_test/flutter_test.dart';
import 'package:tankstellen/features/consumption/data/pump_display_parser.dart';

/// End-to-end parser coverage for French Tokheim / Dresser Wayne pump
/// photos — issue #948. Each test feeds the parser a hand-curated OCR
/// transcription of one of the PNG fixtures in
/// `test/fixtures/pump_displays/` and asserts the transaction values.
///
/// ## Ground-truth source
///
/// The PNG fixtures themselves are the visual truth; the ML Kit text
/// recognizer needs platform channels and can't run inside the `flutter
/// test` harness. We therefore hardcode the OCR text a real Tokheim /
/// Dresser Wayne photo typically produces and feed that STRING through
/// the parser. This keeps the test deterministic and CI-friendly while
/// still exercising the full pollution-strip + pattern-match + positional-
/// inference pipeline.
///
/// The transcriptions cover the pollution sources the parser must strip:
/// the *Note du service de la Métrologie…* header block, card-reader
/// plate labels (*Carte*, *CB*, *Reçu*, *Visa*), regulatory notices
/// (*Contrôle Qualité*, *MMQ*, *Livraison minimale*), and the
/// station-number sticker digit.
///
/// If a future fixture photo produces substantially different OCR, the
/// transcription in this file can be regenerated by running the PNG
/// through ML Kit once and pasting the new string constant here.
void main() {
  const parser = PumpDisplayParser();

  group('PumpDisplayParser — French Tokheim fixtures (#948)', () {
    test('tokheim_79_91eur_36_06l: 79.91 €, 36.06 L, 2.216 €/L', () {
      // Raw OCR text as produced by ML Kit on a French Tokheim pump
      // photo. Contains the metrology header, card-reader overlay,
      // station sticker "3", and a trailing "Diesel" label.
      const ocr = '''
Note du service de la Métrologie
Contrôle Qualité
Livraison minimale 2 L

3
PRIX
€ 79,91
VOLUME
36,06 LITRES
PRIX DU LITRE
€/L 2,216
Diesel
Carte
CB
Visa
Mastercard
Reçu
''';
      final r = parser.parse(ocr);
      expect(r.totalCost, closeTo(79.91, 0.001));
      expect(r.liters, closeTo(36.06, 0.001));
      expect(r.pricePerLiter, closeTo(2.216, 0.001));
      expect(r.pumpNumber, 3);
      expect(r.isConsistent, isTrue);
      expect(r.confidence, greaterThanOrEqualTo(0.9));
    });

    test('tokheim_30_02eur_13_43l: 30.02 €, 13.43 L, 2.235 €/L', () {
      const ocr = '''
Note du service de la Métrologie
MMQ
Livraison minimale 2 L

1
PRIX
€ 30,02
VOLUME
13,43 L
PRIX DU LITRE
€/L 2,235
SP95
Paiement
Carte CB
''';
      final r = parser.parse(ocr);
      expect(r.totalCost, closeTo(30.02, 0.001));
      expect(r.liters, closeTo(13.43, 0.001));
      expect(r.pricePerLiter, closeTo(2.235, 0.001));
      expect(r.pumpNumber, 1);
      expect(r.isConsistent, isTrue);
    });

    test('tokheim_40_04eur_20_03l: 40.04 €, 20.03 L, 1.999 €/L', () {
      const ocr = '''
Note du service de la Métrologie
Contrôle Qualité

4
PRIX
€ 40,04
VOLUME
20,03 LITRES
PRIX DU LITRE
€/L 1,999
E10
Nouveau
Carte
CB
''';
      final r = parser.parse(ocr);
      expect(r.totalCost, closeTo(40.04, 0.001));
      expect(r.liters, closeTo(20.03, 0.001));
      expect(r.pricePerLiter, closeTo(1.999, 0.001));
      expect(r.pumpNumber, 4);
      expect(r.isConsistent, isTrue);
    });

    test('tokheim_10_47eur_5_24l: 10.47 €, 5.24 L, 1.999 €/L', () {
      // Small fill-up. Volume 5,24 is close to the price-per-litre
      // range boundary (<5 excluded), proving the labelled extraction
      // wins over positional inference.
      const ocr = '''
Note du service de la Métrologie
Contrôle Qualité
Livraison minimale 2 L

2
PRIX
€ 10,47
VOLUME
5,24 LITRES
PRIX DU LITRE
€/L 1,999
SP95
Prépaiement
Carte
''';
      final r = parser.parse(ocr);
      expect(r.totalCost, closeTo(10.47, 0.001));
      expect(r.liters, closeTo(5.24, 0.001));
      expect(r.pricePerLiter, closeTo(1.999, 0.001));
      expect(r.pumpNumber, 2);
      expect(r.isConsistent, isTrue);
    });
  });

  group('PumpDisplayParser — Dresser Wayne fixture (#948)', () {
    test('dresser_wayne_32_46eur_14_81l: 32.46 €, 14.81 L, 2.188 €/L', () {
      // Dresser Wayne displays label-value in mixed case and add
      // their own UI overlay ("Nouveau", "Contrôle Qualité").
      const ocr = '''
Note du service de la Métrologie
Contrôle Qualité
MMQ

5
Prix
€ 32,46
Volume
14,81 L
Prix du litre
€/L 2,188
Diesel
Paiement
Carte CB
Espèces
''';
      final r = parser.parse(ocr);
      expect(r.totalCost, closeTo(32.46, 0.001));
      expect(r.liters, closeTo(14.81, 0.001));
      expect(r.pricePerLiter, closeTo(2.188, 0.001));
      expect(r.pumpNumber, 5);
      // 14.81 × 2.188 = 32.404 vs. displayed 32.46 — off by ~5.6 cents.
      // The fixture filename rounds the displayed price, so internal
      // consistency within a 2-cent tolerance isn't expected. We still
      // want all three fields extracted.
      expect(r.hasUsableData, isTrue);
      expect(r.confidence, greaterThanOrEqualTo(0.9));
    });
  });

  group('stripPumpDisplayPollution — helper in isolation', () {
    test('removes the metrology header block up to the next blank line', () {
      const input = '''
Note du service de la Métrologie
Contrôle Qualité
Livraison minimale 2 L

PRIX 30,02 €
''';
      final stripped = stripPumpDisplayPollution(input);
      expect(stripped, isNot(contains('Métrologie')));
      expect(stripped, isNot(contains('Contrôle Qualité')));
      expect(stripped, contains('PRIX 30,02 €'));
    });

    test('strips card-reader overlay labels (Carte, CB, Visa, Reçu)', () {
      const input = '''
PRIX 30,02 €
Carte
CB
Visa
Mastercard
Reçu
Paiement
Espèces
''';
      final stripped = stripPumpDisplayPollution(input);
      expect(stripped, contains('PRIX 30,02 €'));
      expect(stripped, isNot(contains('Carte')));
      expect(stripped, isNot(contains('CB')));
      expect(stripped, isNot(contains('Visa')));
      expect(stripped, isNot(contains('Mastercard')));
      expect(stripped, isNot(contains('Reçu')));
      expect(stripped, isNot(contains('Paiement')));
      expect(stripped, isNot(contains('Espèces')));
    });

    test('strips the French metrology header regardless of accent case', () {
      // Some OCR strips accents to "Metrologie" or renders the
      // circumflex differently.
      const input = '''
Note du service de la Metrologie
bla bla

PRIX 10,00 €
''';
      final stripped = stripPumpDisplayPollution(input);
      expect(stripped, isNot(contains('Metrologie')));
      expect(stripped, contains('PRIX 10,00 €'));
    });

    test('strips lone single-digit station sticker lines', () {
      const input = '''
3
PRIX 30,02 €
''';
      final stripped = stripPumpDisplayPollution(input);
      // The lone digit line is replaced with an empty line so positional
      // inference doesn't pick it up; the line position is preserved.
      final lines = stripped
          .split(RegExp(r'\r?\n'))
          .where((l) => l.trim().isNotEmpty)
          .toList();
      expect(lines, isNot(contains('3')));
      expect(lines, contains('PRIX 30,02 €'));
    });

    test('does not touch an empty or whitespace-only input', () {
      expect(stripPumpDisplayPollution(''), '');
      expect(stripPumpDisplayPollution('   '), '   ');
    });

    test('preserves the German transaction block unchanged', () {
      // Regression check — pollution stripping must not eat any of the
      // German labels or values the existing parser relies on.
      const input = '''
Betrag
€ 58,43
Abgabe
L 31,65
Preis/Liter
€/L 1,846
''';
      final stripped = stripPumpDisplayPollution(input);
      expect(stripped, contains('Betrag'));
      expect(stripped, contains('58,43'));
      expect(stripped, contains('Abgabe'));
      expect(stripped, contains('31,65'));
      expect(stripped, contains('Preis/Liter'));
      expect(stripped, contains('1,846'));
    });
  });
}
