// Copyright (c) 2026 Florian DITTGEN
// SPDX-License-Identifier: MIT

// Tests for `tool/promote_ocr_fixture.dart` (#2519, Epic #2516) — the
// fixture-promotion generator that turns a captured `<slug>.ocrpkg.json`
// into a pure-Dart `extractByLabelAnchor` replay test.
//
// The generator's core (`generateFixtureTest`) is a PURE function — no
// I/O — so it is imported directly and driven on in-memory packages,
// asserting both the happy-path source it emits and the guard rails it
// rejects on. A separate test runs the committed first fixture's package
// through the generator and checks the source matches what is checked in,
// so a drift in the template (or the package) is caught.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/promote_ocr_fixture.dart';

void main() {
  Map<String, dynamic> pumpPackage({
    Object? expected = const {
      'totalCost': 18.59,
      'liters': 23.3,
      'pricePerLiter': 0.798,
      'derived': <String>[],
    },
    String kind = 'pump',
    int schema = 1,
  }) =>
      <String, dynamic>{
        'schema': schema,
        'kind': kind,
        'capturedAt': '2026-05-31T09:00:00.000Z',
        'input': {
          'country': 'FR',
          'profile': {
            'country': 'FR',
            'currency': 'EUR',
            'decimalSeparator': ',',
            'priceMin': 0.5,
            'priceMax': 4.0,
            'volumeMax': 200.0,
            'totalMax': 500.0,
          },
        },
        'mlkit': {
          'flatText': 'PRIX 18,59',
          'blocks': [
            {
              'text': 'PRIX',
              'box': [40, 100, 130, 130]
            },
            {
              'text': '18,59',
              'box': [40, 140, 200, 185]
            },
          ],
        },
        'expected': ?expected,
      };

  group('generateFixtureTest — happy path', () {
    test('emits a const block list, profile, and closeTo asserts', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(),
        packagePath: 'test/fixtures/pump_displays/fr_tokheim/foo.ocrpkg.json',
      );
      expect(r.error, isNull);
      expect(r.slug, 'foo');
      expect(r.country, 'FR');
      expect(r.blockCount, 2);
      final src = r.source!;
      expect(src, contains('GENERATED by'));
      expect(src, contains('const <RecognizedTextBlock>['));
      expect(src, contains("text: 'PRIX'"));
      expect(src, contains('OcrLocaleProfile('));
      expect(src, contains('extractByLabelAnchor(blocks, profile: profile)'));
      expect(src, contains('closeTo(18.59, 0.001)'));
      expect(src, contains('closeTo(23.3, 0.001)'));
      expect(src, contains('closeTo(0.798, 0.001)'));
      // No derived → asserts emptiness.
      expect(src, contains('expect(r.derived, isEmpty)'));
    });

    test('a derived field maps onto its PumpField contains-assert', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(expected: const {
          'totalCost': 18.59,
          'liters': 23.3,
          'derived': ['pricePerLiter'],
        }),
        packagePath: 'a/b/c/derived.ocrpkg.json',
      );
      expect(r.error, isNull);
      expect(r.source, contains('contains(PumpField.pricePerLitre)'));
    });

    test('a null profile (no country) emits a null OcrLocaleProfile', () {
      final pkg = pumpPackage();
      (pkg['input'] as Map).remove('profile');
      (pkg['input'] as Map).remove('country');
      final r = generateFixtureTest(pkg: pkg, packagePath: 'x/noprofile.json');
      expect(r.error, isNull);
      expect(r.country, isNull);
      expect(r.source, contains('const OcrLocaleProfile? profile = null;'));
    });

    test('a leading-digit slug is prefixed to a valid Dart identifier', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(),
        packagePath: '9498.ocrpkg.json',
      );
      expect(r.slug, 'f_9498');
    });
  });

  group('generateFixtureTest — guard rails', () {
    test('rejects an unsupported schema', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(schema: 2),
        packagePath: 'x.ocrpkg.json',
      );
      expect(r.error, contains('schema'));
      expect(r.source, isNull);
    });

    test('rejects a receipt package (not a label-anchor replay)', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(kind: 'receipt'),
        packagePath: 'x.ocrpkg.json',
      );
      expect(r.error, contains('receipt'));
    });

    test('rejects a package with no expected values', () {
      final r = generateFixtureTest(
        pkg: pumpPackage(expected: null),
        packagePath: 'x.ocrpkg.json',
      );
      expect(r.error, contains('expected'));
    });

    test('rejects empty mlkit.blocks', () {
      final pkg = pumpPackage();
      (pkg['mlkit'] as Map)['blocks'] = <dynamic>[];
      final r = generateFixtureTest(pkg: pkg, packagePath: 'x.ocrpkg.json');
      expect(r.error, contains('empty'));
    });
  });

  group('the committed first fixture is in sync with the generator', () {
    const pkgPath = 'test/fixtures/pump_displays/fr_tokheim/'
        'fr_tokheim_18_59eur_23_30l.ocrpkg.json';
    const genPath = 'test/features/consumption/data/ocr/fixtures/'
        'fr_tokheim_18_59eur_23_30l_fixture_test.dart';

    test('regenerating the package reproduces the committed test verbatim',
        () {
      final pkg =
          jsonDecode(File(pkgPath).readAsStringSync()) as Map<String, dynamic>;
      final r = generateFixtureTest(pkg: pkg, packagePath: pkgPath);
      expect(r.error, isNull, reason: 'the first fixture must promote cleanly');
      expect(File(genPath).readAsStringSync(), r.source,
          reason: 'run `dart run tool/promote_ocr_fixture.dart $pkgPath` and '
              'commit the regenerated test');
    });
  });
}
