import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:tankstellen/core/notifications/notification_payload.dart';

void main() {
  group('NotificationPayload (#1012 phase 3 — deep-link payload)', () {
    test('encode produces the documented {k,s,c} JSON shape', () {
      const payload = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-001',
        country: 'de',
      );

      final raw = payload.encode();
      // jsonDecode keeps the fields independent of map ordering — pin
      // the schema by inspecting decoded keys, not by string matching.
      final decoded = jsonDecode(raw) as Map<String, dynamic>;
      expect(decoded.keys.toSet(), {'k', 's', 'c'},
          reason:
              'Wire format is the compact {k,s,c} object — not {kind,stationId,country}.');
      expect(decoded['k'], 'radius');
      expect(decoded['s'], 'de-001');
      expect(decoded['c'], 'de');
    });

    test('encode → tryDecode round-trips losslessly', () {
      const original = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'it-42-roma',
        country: 'it',
      );
      final round = NotificationPayload.tryDecode(original.encode());

      expect(round, isNotNull);
      expect(round, original,
          reason: 'NotificationPayload equality is value-based — round-trip '
              'must produce a value-equal instance.');
    });

    test('tryDecode returns null for a non-string null input', () {
      expect(NotificationPayload.tryDecode(null), isNull);
    });

    test('tryDecode returns null for an empty string', () {
      expect(NotificationPayload.tryDecode(''), isNull);
    });

    test('tryDecode returns null for invalid JSON', () {
      expect(NotificationPayload.tryDecode('{not json'), isNull);
    });

    test('tryDecode returns null when JSON is not an object', () {
      // A bare list or string is valid JSON but not a payload.
      expect(NotificationPayload.tryDecode('[1,2,3]'), isNull);
      expect(NotificationPayload.tryDecode('"plain"'), isNull);
    });

    test('tryDecode returns null when k is missing', () {
      expect(
        NotificationPayload.tryDecode('{"s":"id","c":"de"}'),
        isNull,
        reason: 'A schema-shaped payload must surface every required key — '
            'a missing kind means the tap handler cannot route safely.',
      );
    });

    test('tryDecode returns null when s is missing', () {
      expect(
        NotificationPayload.tryDecode('{"k":"radius","c":"de"}'),
        isNull,
      );
    });

    test('tryDecode returns null when c is missing', () {
      expect(
        NotificationPayload.tryDecode('{"k":"radius","s":"id"}'),
        isNull,
      );
    });

    test('tryDecode returns null when any field is empty', () {
      expect(
        NotificationPayload.tryDecode('{"k":"","s":"id","c":"de"}'),
        isNull,
      );
      expect(
        NotificationPayload.tryDecode('{"k":"radius","s":"","c":"de"}'),
        isNull,
      );
      expect(
        NotificationPayload.tryDecode('{"k":"radius","s":"id","c":""}'),
        isNull,
      );
    });

    test('tryDecode returns null when fields are not strings', () {
      // Payload is generated by the runner so this is paranoid, but a
      // future server-side sender or a corrupt OS-level relay could
      // supply numbers — degrade rather than crash.
      expect(
        NotificationPayload.tryDecode('{"k":1,"s":"id","c":"de"}'),
        isNull,
      );
    });

    test('toRouterPath returns /station/:id for radius kind', () {
      const payload = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'shell-456',
        country: 'de',
      );
      expect(payload.toRouterPath(), '/station/shell-456');
    });

    test('toRouterPath returns null for unknown kinds', () {
      // An unrecognised kind reaches the resolver after a future
      // notification type ships with an older app version. Returning
      // null lets the launch listener no-op rather than crashing.
      const payload = NotificationPayload(
        kind: 'price_drop_v2',
        stationId: 'shell-456',
        country: 'de',
      );
      expect(payload.toRouterPath(), isNull);
    });

    test('value equality and hashCode match for identical fields', () {
      const a = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-001',
        country: 'de',
      );
      const b = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-001',
        country: 'de',
      );
      expect(a, equals(b));
      expect(a.hashCode, equals(b.hashCode));
    });

    test('value equality differs when any field differs', () {
      const a = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-001',
        country: 'de',
      );
      const differentStation = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-002',
        country: 'de',
      );
      const differentCountry = NotificationPayload(
        kind: NotificationPayload.kindRadius,
        stationId: 'de-001',
        country: 'it',
      );
      expect(a, isNot(equals(differentStation)));
      expect(a, isNot(equals(differentCountry)));
    });
  });
}
