// Copyright (c) 2026 Florian DITTGEN
// SPDX-License-Identifier: MIT

// GENERATED by `tool/promote_ocr_fixture.dart` (#2519) from
// `test/fixtures/pump_displays/fr_tokheim/fr_tokheim_18_59eur_23_30l.ocrpkg.json`.
// DO NOT EDIT BY HAND — re-run the generator and commit the
// diff to refresh. A structural twin of
// `label_anchored_extractor_test.dart`: it replays the BAKED
// ML Kit blocks through the pure-Dart `extractByLabelAnchor`
// (no platform channel, runs in CI) and asserts the package's
// `expected` read.
//
// Captured: 2026-05-31T09:00:00.000Z

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:tankstellen/features/consumption/data/ocr/label_anchored_extractor.dart';
import 'package:tankstellen/features/consumption/data/ocr/pump_ocr_config.dart';
import 'package:tankstellen/features/consumption/data/ocr/recognized_text_block.dart';

void main() {
  // --- baked ML Kit blocks (rebuilt from mlkit.blocks) -------
  List<RecognizedTextBlock> bakedBlocks() => const <RecognizedTextBlock>[
        RecognizedTextBlock(
          text: 'PRIX',
          box: OcrBox(left: 40.0, top: 100.0, right: 130.0, bottom: 130.0),
        ),
        RecognizedTextBlock(
          text: '18,59',
          box: OcrBox(left: 40.0, top: 140.0, right: 200.0, bottom: 185.0),
        ),
        RecognizedTextBlock(
          text: 'VOLUME',
          box: OcrBox(left: 40.0, top: 220.0, right: 170.0, bottom: 250.0),
        ),
        RecognizedTextBlock(
          text: '23,30',
          box: OcrBox(left: 40.0, top: 260.0, right: 200.0, bottom: 305.0),
        ),
        RecognizedTextBlock(
          text: 'PRIX DU LITRE',
          box: OcrBox(left: 40.0, top: 340.0, right: 230.0, bottom: 370.0),
        ),
        RecognizedTextBlock(
          text: '0,798',
          box: OcrBox(left: 40.0, top: 380.0, right: 180.0, bottom: 420.0),
        ),
        RecognizedTextBlock(
          text: 'Note du service de la Métrologie',
          box: OcrBox(left: 400.0, top: 20.0, right: 720.0, bottom: 50.0),
        ),
        RecognizedTextBlock(
          text: 'Seules les indications de prix',
          box: OcrBox(left: 400.0, top: 55.0, right: 760.0, bottom: 80.0),
        ),
        RecognizedTextBlock(
          text: 'TOKHEIM',
          box: OcrBox(left: 300.0, top: 600.0, right: 460.0, bottom: 660.0),
        ),
        RecognizedTextBlock(
          text: 'Vmin = 5L',
          box: OcrBox(left: 700.0, top: 20.0, right: 820.0, bottom: 55.0),
        ),
        RecognizedTextBlock(
          text: '3',
          box: OcrBox(left: 720.0, top: 600.0, right: 760.0, bottom: 660.0),
        ),
      ];

  const profile = OcrLocaleProfile(
    country: 'FR',
    currency: 'EUR',
    decimalSeparator: ',',
    priceMin: 0.5,
    priceMax: 4.0,
    volumeMax: 200.0,
    totalMax: 500.0,
  );

  group('#2519 fixture replay — fr_tokheim_18_59eur_23_30l (FR)', () {
    test('replays baked blocks through extractByLabelAnchor', () {
      final blocks = bakedBlocks();
      final r = extractByLabelAnchor(blocks, profile: profile);
      expect(r.totalCost, closeTo(18.59, 0.001));
      expect(r.liters, closeTo(23.3, 0.001));
      expect(r.pricePerLiter, closeTo(0.798, 0.001));
      // No field flagged DERIVED in the expected read.
      expect(r.derived, isEmpty);
    });

    test('source image is committed alongside the package', () {
      expect(File('test/fixtures/pump_displays/fr_tokheim/fr_tokheim_18_59eur_23_30l.jpg').existsSync(), isTrue,
          reason: 'the captured source frame must be committed as the fixture');
    });
  });
}
