// Copyright (c) 2026 Florian DITTGEN
// SPDX-License-Identifier: AGPL-3.0-or-later

/// Licence lint: every source file declares AGPL-3.0-or-later, and
/// nothing declares anything else (ADR 0028, #4444).
///
/// ADR 0028 relicensed the whole repository from MIT and said every SPDX
/// header becomes `AGPL-3.0-or-later`. That was a 4420-file sweep done
/// by machine in one commit — which is exactly the kind of change that
/// finishes 99 % of the way and is believed to have finished entirely.
/// DesKilo's equivalent sweep missed ten files (the Gemfile, three
/// fastlane files, two store-upload scripts, the GMS audit, the icon
/// generator, the installer authoring and a workflow) and stayed wrong
/// for two weeks because nothing checked.
///
/// The second assertion matters as much as the first: **a file that
/// declares MIT is worse than a file that declares nothing**, because it
/// is a false statement about terms someone may rely on. A reader who
/// wants to close-source that file would believe they may, and nothing
/// would ever tell them otherwise.
///
/// There is no baseline here on purpose: the whole tree was swept in the
/// same commit, so there is no backlog to grandfather.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _spdx = 'SPDX-License-Identifier';
const _licence = 'AGPL-3.0-or-later';

/// Trees whose hand-written sources must carry the header.
const _roots = <String>[
  'lib',
  'test',
  'tool',
  'tools',
  'scripts',
  'supabase',
  'integration_test',
  'test_driver',
  '.github/workflows',
];

const _extensions = <String>['.dart', '.sh', '.py', '.sql', '.yml', '.yaml'];

/// Individually-named files outside [_roots] — the build and packaging
/// surface. This is where a sweep loses files, precisely because nobody
/// thinks of the Gemfile or the analyzer config as "source".
const _alsoCheck = <String>[
  'Gemfile',
  'pubspec.yaml',
  'analysis_options.yaml',
  'l10n.yaml',
  'build.yaml',
  'dart_test.yaml',
];

/// Files exempt from carrying the header, each for a stated reason.
/// This list may only ever SHRINK.
const _exempt = <String, String>{
  'docs/decisions/0007-mit-license-choice.md':
      'records the superseded MIT decision; quoting the old identifier is '
          'the point of the document',
  'test/core/sync/goldens/migration_sql_fully_provisioned.golden.sql':
      'generated by schema_sql_golden_test from buildMigrationSql',
  'test/core/sync/goldens/migration_sql_empty_schema.golden.sql':
      'generated by schema_sql_golden_test from buildMigrationSql',
  'tool/gr_fuel/fuelpricesgr/enums.py':
      'vendored from mavroprovato/fuelpricesgr under MIT — upstream '
          'copyright, so stamping our own header on it would be a false '
          'claim',
  'tool/gr_fuel/fuelpricesgr/__init__.py': 'vendored — see enums.py',
  'tool/gr_fuel/fuelpricesgr/parser.py': 'vendored — see enums.py',
};

/// Codegen output. `build_runner` emits no SPDX header and the file is
/// never hand-edited, so it takes the licence of the source it is
/// generated from by derivation, not by declaration.
bool _generated(String path) =>
    path.endsWith('.g.dart') ||
    path.endsWith('.freezed.dart') ||
    path.contains('lib/l10n/') ||
    path.contains('app_localizations');

/// The header is a header: read a fixed PREFIX, not the whole file, so a
/// stray mention deep in a fixture cannot satisfy the rule, and so the
/// sweep does not decode megabytes to inspect eight lines.
String _headOf(File file) {
  final handle = file.openSync();
  try {
    return String.fromCharCodes(handle.readSync(600));
  } finally {
    handle.closeSync();
  }
}

List<File> _sources() {
  final out = <File>[];
  for (final root in _roots) {
    final dir = Directory(root);
    if (!dir.existsSync()) continue;
    out.addAll(
      dir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => _extensions.any(f.path.endsWith))
          .where((f) => !_generated(f.path))
          .where((f) => !_exempt.containsKey(f.path)),
    );
  }
  out.addAll(_alsoCheck.map(File.new).where((f) => f.existsSync()));
  return out..sort((a, b) => a.path.compareTo(b.path));
}

void main() {
  group('SPDX headers — one licence, both directions (ADR 0028)', () {
    test('the walk is not vacuous', () {
      expect(_sources().length, greaterThan(3000),
          reason: 'the walk found almost nothing — a root was renamed and '
              'this gate stopped guarding');
    });

    test('every source file declares a licence', () {
      final missing = _sources()
          .where((f) => !_headOf(f).contains(_spdx))
          .map((f) => f.path)
          .toList();
      expect(missing, isEmpty,
          reason: 'No $_spdx header in the first 600 bytes:\n'
              '${missing.join('\n')}\n\n'
              "Add `$_spdx: $_licence` in the file's comment syntax — `//` "
              'for Dart, `#` for YAML/shell/Python, `--` for SQL. There is '
              'no baseline here on purpose.');
    });

    test('and it declares $_licence, not something else', () {
      final wrong = <String>[];
      for (final file in _sources()) {
        final head = _headOf(file);
        if (!head.contains(_spdx)) continue; // reported by the test above
        if (!head.contains('$_spdx: $_licence')) {
          final line = head
              .split('\n')
              .firstWhere((l) => l.contains(_spdx), orElse: () => '')
              .trim();
          wrong.add('${file.path}: $line');
        }
      }
      expect(wrong, isEmpty,
          reason: 'These declare a licence other than $_licence (ADR 0028). '
              'A stale MIT header is a false statement about terms someone '
              'may rely on — worse than no header at all, because a reader '
              'would believe they may close-source the file:\n'
              '${wrong.join('\n')}');
    });

    test('no exemption has rotted — every exempt file still exists', () {
      final gone = _exempt.keys.where((p) => !File(p).existsSync()).toList();
      expect(gone, isEmpty,
          reason: 'remove these from _exempt, they no longer exist: '
              '${gone.join(', ')}');
    });

    test('every exemption states a reason', () {
      for (final entry in _exempt.entries) {
        expect(entry.value.trim(), isNotEmpty,
            reason: '${entry.key} is exempt with no stated reason');
      }
    });
  });
}
