// Copyright (c) 2026 Florian DITTGEN
// SPDX-License-Identifier: MIT
//
// #4005 — the wiki is in the repository now, so it can be checked the
// way the code is.
//
// Sparkilo's user guide exists in seven languages. Before this it lived
// only in the GitHub wiki, where nothing compared them: a page added to
// the English guide and forgotten in Danish looked exactly like a page
// that was never meant to exist in Danish. Seven copies drift silently
// and nobody finds out until a reader does.
//
// These are the two checks that catch drift without pretending to check
// translation quality, which no test can do:
//
//  * every language carries the same SET of pages;
//  * a page's images exist in the wiki's own image folders.
//
// Deliberately NOT checked: heading counts or word counts. A translation
// that says the same thing in fewer sentences is a good translation, and
// a lint that forbids it teaches people to pad.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _languages = ['da', 'de', 'en', 'es', 'fr', 'it', 'pt'];
const _wiki = 'docs/wiki';

/// `User-en-Finding-Stations.md` → `Finding-Stations`.
String? _pageOf(String name, String language) {
  final prefix = 'User-$language-';
  if (!name.startsWith(prefix) || !name.endsWith('.md')) return null;
  return name.substring(prefix.length, name.length - 3);
}

Set<String> _pagesFor(String language) {
  final dir = Directory(_wiki);
  return {
    for (final f in dir.listSync().whereType<File>())
      ?_pageOf(f.uri.pathSegments.last, language),
  };
}

void main() {
  test('the wiki is in the repository', () {
    expect(Directory(_wiki).existsSync(), isTrue,
        reason: 'docs/wiki is the source of truth; the GitHub wiki is a '
            'mirror of it. See docs/guides/wiki-mirror.md.');
  });

  test('every language carries the same set of user pages', () {
    final english = _pagesFor('en');
    expect(english, isNotEmpty, reason: 'no English user pages found');
    final problems = <String>[];
    for (final language in _languages) {
      if (language == 'en') continue;
      final pages = _pagesFor(language);
      for (final missing in english.difference(pages)) {
        problems.add('$language is missing User-$language-$missing.md');
      }
      for (final extra in pages.difference(english)) {
        problems.add('$language has User-$language-$extra.md with no '
            'English counterpart');
      }
    }
    expect(problems, isEmpty,
        reason: 'the user guide must exist in every language it claims to '
            'support, or the claim is false:\n${problems.join('\n')}');
  });

  test('an image a page references exists (#4044)', () {
    // The markdown lives here and the images live in the wiki repository,
    // so this check has no folder to look at. It used to bail out when the
    // folders were absent — which in this repo is ALWAYS — so a test named
    // "an image a page references exists" asserted nothing, ever, and a
    // page could point at an image that was never published without
    // anything noticing. Same failure class as #2348.
    //
    // `docs/wiki/images.manifest` is the hermetic stand-in: every image the
    // published wiki carries, regenerated by `tool/wiki_image_manifest.dart`
    // in the same commit as the markdown that points at it.
    final manifest = File('$_wiki/images.manifest');
    expect(manifest.existsSync(), isTrue,
        reason: 'docs/wiki/images.manifest is the only thing standing '
            'between a renamed image and a broken user guide in seven '
            'languages — regenerate it, never delete it');
    final have = manifest
        .readAsLinesSync()
        .where((l) => l.isNotEmpty && !l.startsWith('#'))
        .toSet();
    expect(have, isNotEmpty, reason: 'empty manifest = the guard is blind');

    final reference = RegExp(r'(?:src="|\]\()((?:guide|screenshots)/[^")]+)');
    final missing = <String>[];
    var references = 0;
    for (final f in Directory(_wiki).listSync().whereType<File>()) {
      if (!f.path.endsWith('.md')) continue;
      for (final m in reference.allMatches(f.readAsStringSync())) {
        references++;
        if (!have.contains(m.group(1))) {
          missing.add('${f.uri.pathSegments.last} → ${m.group(1)}');
        }
      }
    }
    // Fidelity self-check (#2348): a guard that matches nothing reads as
    // clean just like a guard that matches everything and finds no fault.
    expect(references, greaterThan(100),
        reason: 'only $references image references found across the guide — '
            'the matcher has drifted from the markdown and would report a '
            'false green');

    expect(missing, isEmpty,
        reason: 'a page points at an image the published wiki does not '
            'carry:\n${missing.join('\n')}');
  });

  test('the manifest matches the real wiki when a clone is at hand (#4044)',
      () {
    // The manifest can only rot if nothing compares it to the truth. When a
    // sibling wiki clone exists, do exactly that — recursively, because the
    // images that matter most (`guide/full/`) live one level down and the
    // previous non-recursive scan would have reported every one of them
    // missing.
    final wiki = Directory('../tankstellen.wiki');
    if (!wiki.existsSync()) return; // CI has no clone; the guard above stands
    final actual = <String>{};
    for (final folder in const ['guide', 'screenshots']) {
      final dir = Directory('${wiki.path}/$folder');
      if (!dir.existsSync()) continue;
      for (final e in dir.listSync(recursive: true).whereType<File>()) {
        final rel =
            e.path.substring(wiki.path.length + 1).replaceAll(r'\', '/');
        if (rel.startsWith('guide/_tooling/')) continue;
        actual.add(rel);
      }
    }
    final recorded = File('$_wiki/images.manifest')
        .readAsLinesSync()
        .where((l) => l.isNotEmpty && !l.startsWith('#'))
        .toSet();
    expect(recorded, equals(actual),
        reason: 'docs/wiki/images.manifest has drifted from the wiki — '
            'dart run tool/wiki_image_manifest.dart --write');
  });
}
