#!/usr/bin/env bash
# Copyright (c) 2026 Florian DITTGEN
# SPDX-License-Identifier: MIT

# audit_no_gms.sh — prove the F-Droid (`fdroid`) flavor is free of proprietary
# Google Mobile Services (#2574).
#
# Two independent layers, EITHER of which fails the audit:
#
#   (A) Dependency-graph layer (always runs): resolve the fdroid release runtime
#       classpath via Gradle and assert it contains NO `com.google.android.gms`
#       and NO `com.google.mlkit` coordinates. This is the authoritative proof —
#       it is what the official fdroiddata reproducible build inspects.
#
#   (B) Bytecode layer (runs when an APK path is given): unzip the APK, dexdump
#       every classesN.dex, and assert no `Lcom/google/android/gms/...;` or
#       `Lcom/google/mlkit/...;` type reference survives into the shipped dex.
#       Falls back to `strings` on the dex when dexdump is unavailable.
#
# Usage:
#   scripts/audit_no_gms.sh                 # layer A only (dependency graph)
#   scripts/audit_no_gms.sh path/to.apk     # layer A + layer B on the APK
#
# Exit codes: 0 = clean, 1 = a GMS/MLKit hit was found, 2 = setup/usage error.

set -euo pipefail

# Resolve repo root so the script works from any CWD (CI, hooks, local).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Pattern that matches a GMS or ML Kit coordinate in `:app:dependencies` output
# (group:artifact form) and a dexed type descriptor (Lcom/google/...;).
GMS_GRAPH_PATTERN='com\.google\.android\.gms|com\.google\.mlkit'
GMS_DEX_PATTERN='Lcom/google/android/gms/|Lcom/google/mlkit/'

APK_PATH="${1:-}"
FAILED=0

echo "==> [A] fdroid runtime classpath — must contain no GMS/MLKit"

# This is a Flutter project: the Gradle wrapper lives at android/gradlew (it is
# generated by `flutter pub get`/`flutter build`, and is .gitignored), NOT at
# the repo root. So gradle MUST be invoked from inside android/ — `-p android`
# from the repo root would still try to exec a non-existent ${REPO_ROOT}/gradlew.
ANDROID_DIR="${REPO_ROOT}/android"
if [[ ! -x "${ANDROID_DIR}/gradlew" ]]; then
  echo "ERROR: ${ANDROID_DIR}/gradlew not found or not executable." >&2
  echo "       Run 'flutter pub get' (or a 'flutter build') first to generate it." >&2
  exit 2
fi

# Resolve one fdroid runtime classpath via `app:dependencies` (run from android/,
# where ./gradlew lives). `--console=plain` keeps the output greppable.
# NB: do NOT pass `-q`/`--quiet` here — Gradle's `--quiet` can suppress the very
# dependency tree we grep, which would silently produce a false "OK". The extra
# lifecycle noise never matches the GMS coordinate pattern.
#
# We prefer the RELEASE classpath (fdroidReleaseRuntimeClasspath) — that is what
# the shipped F-Droid APK resolves. But resolving the release classpath can fail
# in keyless environments (the #48 signing guard throws on a release context
# without a keystore). The GMS/MLKit exclude is FLAVOR-scoped (it applies to
# fdroidImplementation + every fdroid*RuntimeClasspath), so the DEBUG classpath
# proves the exact same thing. Fall back to it when release resolution fails.
run_app_dependencies() { # $1 = configuration name
  (cd "${ANDROID_DIR}" && ./gradlew --console=plain \
    app:dependencies --configuration "$1") 2>&1
}

GRAPH_CONFIG="fdroidReleaseRuntimeClasspath"
if ! GRAPH_OUT="$(run_app_dependencies "${GRAPH_CONFIG}")"; then
  echo "NOTE: could not resolve ${GRAPH_CONFIG} (likely the #48 keyless-release" >&2
  echo "      guard); falling back to fdroidDebugRuntimeClasspath — the exclude" >&2
  echo "      is flavor-scoped, so the debug classpath proves it too." >&2
  GRAPH_CONFIG="fdroidDebugRuntimeClasspath"
  if ! GRAPH_OUT="$(run_app_dependencies "${GRAPH_CONFIG}")"; then
    echo "ERROR: gradle dependency resolution failed for both the release and" >&2
    echo "       debug fdroid runtime classpaths:" >&2
    echo "${GRAPH_OUT}" >&2
    exit 2
  fi
fi

if echo "${GRAPH_OUT}" | grep -Eq "${GMS_GRAPH_PATTERN}"; then
  echo "FAIL: GMS/MLKit coordinates present on ${GRAPH_CONFIG}:" >&2
  echo "${GRAPH_OUT}" | grep -E "${GMS_GRAPH_PATTERN}" >&2
  FAILED=1
else
  echo "OK: no com.google.android.gms / com.google.mlkit on ${GRAPH_CONFIG}."
fi

if [[ -n "${APK_PATH}" ]]; then
  echo "==> [B] dex bytecode audit — ${APK_PATH}"
  if [[ ! -f "${APK_PATH}" ]]; then
    echo "ERROR: APK not found: ${APK_PATH}" >&2
    exit 2
  fi

  WORK_DIR="$(mktemp -d)"
  trap 'rm -rf "${WORK_DIR}"' EXIT
  unzip -q -o "${APK_PATH}" 'classes*.dex' -d "${WORK_DIR}" || {
    echo "ERROR: failed to extract classes*.dex from APK." >&2
    exit 2
  }

  # Locate dexdump (Android build-tools). Optional — fall back to `strings`.
  # The build-tools lookup must be glob-safe: `${SDK_ROOT}/build-tools/*/dexdump`
  # can expand to NOTHING (no SDK, or a build-tools dir with no dexdump), so we
  # enumerate with `ls` + version-sort + an explicit `-x` test rather than a raw
  # glob that would silently leave a literal unexpanded path behind.
  DEXDUMP_BIN=""
  if command -v dexdump >/dev/null 2>&1; then
    DEXDUMP_BIN="$(command -v dexdump)"
  else
    SDK_ROOT="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
    if [[ -n "${SDK_ROOT}" && -d "${SDK_ROOT}/build-tools" ]]; then
      # newest build-tools first; take the first one that actually has dexdump.
      while IFS= read -r ver; do
        [[ -n "${ver}" ]] || continue
        if [[ -x "${SDK_ROOT}/build-tools/${ver}/dexdump" ]]; then
          DEXDUMP_BIN="${SDK_ROOT}/build-tools/${ver}/dexdump"
          break
        fi
      done < <(ls -1 "${SDK_ROOT}/build-tools" 2>/dev/null | sort -Vr)
    fi
  fi

  # `strings` may be absent on a minimal runner; `grep -a` on the binary dex is
  # an equivalent last-resort (the type descriptors are stored as plain ASCII).
  STRINGS_BIN=""
  command -v strings >/dev/null 2>&1 && STRINGS_BIN="$(command -v strings)"

  DEX_HIT=0
  DEX_COUNT=0
  shopt -s nullglob
  for dex in "${WORK_DIR}"/classes*.dex; do
    DEX_COUNT=$((DEX_COUNT + 1))
    if [[ -n "${DEXDUMP_BIN}" ]]; then
      if "${DEXDUMP_BIN}" "${dex}" 2>/dev/null | grep -Eq "${GMS_DEX_PATTERN}"; then
        echo "FAIL: GMS/MLKit type references in $(basename "${dex}") (dexdump):" >&2
        "${DEXDUMP_BIN}" "${dex}" 2>/dev/null | grep -E "${GMS_DEX_PATTERN}" | sort -u | head -40 >&2
        DEX_HIT=1
      fi
    else
      # Fallback: raw type descriptors are stored as ASCII strings in the dex.
      # Prefer `strings`; if absent, scan the binary directly with `grep -a`.
      # `|| true`: a no-match grep returns 1, which under `set -euo pipefail`
      # would abort the whole audit on a CLEAN dex. We treat no-match as success
      # (empty SCAN_OUT) and only fail below when SCAN_OUT is non-empty.
      if [[ -n "${STRINGS_BIN}" ]]; then
        SCAN_OUT="$("${STRINGS_BIN}" -a "${dex}" | { grep -E "${GMS_DEX_PATTERN}" || true; } | sort -u | head -40)"
      else
        SCAN_OUT="$({ grep -a -E "${GMS_DEX_PATTERN}" "${dex}" || true; } | sort -u | head -40)"
      fi
      if [[ -n "${SCAN_OUT}" ]]; then
        echo "FAIL: GMS/MLKit type strings in $(basename "${dex}") (strings fallback):" >&2
        echo "${SCAN_OUT}" >&2
        DEX_HIT=1
      fi
    fi
  done
  shopt -u nullglob

  if [[ "${DEX_COUNT}" -eq 0 ]]; then
    echo "ERROR: no classes*.dex extracted from ${APK_PATH} — cannot run the dex audit." >&2
    exit 2
  fi
  if [[ -z "${DEXDUMP_BIN}" ]]; then
    echo "NOTE: dexdump not found — used 'strings' fallback (set ANDROID_HOME for dexdump)."
  fi
  if [[ "${DEX_HIT}" -eq 0 ]]; then
    echo "OK: no GMS/MLKit type references in any dex."
  else
    FAILED=1
  fi
fi

if [[ "${FAILED}" -ne 0 ]]; then
  echo "==> AUDIT FAILED: the fdroid flavor still references GMS/MLKit." >&2
  exit 1
fi

echo "==> AUDIT PASSED: fdroid flavor is GMS/MLKit-free."
exit 0
