#!/usr/bin/env bash
# Copyright (c) 2026 Florian DITTGEN
# SPDX-License-Identifier: MIT

# audit_no_gms.sh — prove the F-Droid (`fdroid`) flavor is free of proprietary
# Google libraries: Google Mobile Services, ML Kit (#2574), Play Core (the
# In-App Review API pulled by in_app_review, #3069) AND Sentry (the Tracking
# anti-feature, #3492).
#
# Layers, ANY of which fails the audit:
#
#   (A) Dependency-graph layer (always runs): resolve the fdroid release runtime
#       classpath via Gradle and assert it contains NO `com.google.android.gms`,
#       NO `com.google.mlkit`, NO `com.google.android.play` and NO `io.sentry`
#       coordinates. This is the authoritative proof — it is what the official
#       fdroiddata reproducible build inspects.
#
#   (B) Bytecode layer (runs when an APK path is given): unzip the APK, dexdump
#       every classesN.dex, and assert no `Lcom/google/android/gms/...;`,
#       `Lcom/google/mlkit/...;`, `Lcom/google/android/play/...;` or
#       `Lio/sentry/...;` class is DEFINED in the shipped dex. Falls back to
#       `strings` on the dex when dexdump is unavailable.
#
#   (C) Strict REFERENCE gate (#3480, epic #3473): on a RELEASE APK (basename
#       contains `release`, or `--strict-refs` is passed) even a dangling type
#       REFERENCE fails — the same bar as F-Droid's `check apk` scanner, which
#       rejected MR !42093 on exactly such references. Feasible since the
#       epic-#3473 pubspec-override mechanism removed every referrer: a release
#       fdroid dex audits `gms:0 mlkit:0 play:0 sentry:0`. A DEBUG APK keeps
#       the definition-only bar (R8 is off, so Flutter's own embedding retains
#       inert Play-Core deferred-components references there).
#
# Usage:
#   scripts/audit_no_gms.sh                        # layer A only
#   scripts/audit_no_gms.sh path/to.apk            # + B (+ C when 'release' in name)
#   scripts/audit_no_gms.sh path/to.apk --strict-refs   # force layer C
#
# Exit codes: 0 = clean, 1 = a GMS/MLKit/Play-Core/Sentry hit was found,
#             2 = setup/usage error.

set -euo pipefail

# Resolve repo root so the script works from any CWD (CI, hooks, local).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Pattern that matches a GMS, ML Kit, Play Core or Sentry coordinate in
# `:app:dependencies` output (group:artifact form). #3480 — io.sentry added:
# the fdroid flavor compiles Sentry out entirely (#3492).
GMS_GRAPH_PATTERN='com\.google\.android\.gms|com\.google\.mlkit|com\.google\.android\.play|io\.sentry'
# A GMS/ML Kit/Play-Core/Sentry *type descriptor* anywhere in the dex
# (definition OR reference). NB: the project's own plugin packages are
# `com.google_mlkit_*` (underscore) — this `com/google/(android/gms|mlkit|
# android/play)/` pattern (slash after google) never matches those, only the
# proprietary `com.google.android.gms` / `com.google.mlkit` /
# `com.google.android.play` / `io.sentry`.
GMS_DEX_PATTERN='Lcom/google/android/gms/|Lcom/google/mlkit/|Lcom/google/android/play/|Lio/sentry/'
# A GMS/ML Kit/Play-Core/Sentry *class definition* (proprietary/tracking
# bytecode actually shipped). dexdump prints `  Class descriptor  :
# 'Lcom/google/...;'` for every class DEFINED in the dex. This is the
# authoritative "no proprietary Google code in the APK" test — see the long
# note at the head of layer B below for why a dangling *reference* (to an
# absent class) fails only in strict mode (layer C).
GMS_DEX_DEF_PATTERN="Class descriptor *: *'Lcom/google/android/gms/|Class descriptor *: *'Lcom/google/mlkit/|Class descriptor *: *'Lcom/google/android/play/|Class descriptor *: *'Lio/sentry/"

APK_PATH="${1:-}"
# #3480 — layer C (fail on dangling REFERENCES, the F-Droid `check apk` bar).
# Forced with --strict-refs; auto-enabled for a release-named APK, where the
# epic-#3473 override mechanism + R8 guarantee a 0-reference dex.
STRICT_REFS=0
if [[ "${2:-}" == "--strict-refs" ]]; then
  STRICT_REFS=1
elif [[ -n "${APK_PATH}" && "$(basename "${APK_PATH}")" == *release* ]]; then
  STRICT_REFS=1
fi
FAILED=0

echo "==> [A] fdroid runtime classpath — must contain no GMS/MLKit/Play-Core/Sentry"

# This is a Flutter project: the Gradle wrapper lives at android/gradlew (it is
# generated by `flutter pub get`/`flutter build`, and is .gitignored), NOT at
# the repo root. So gradle MUST be invoked from inside android/ — `-p android`
# from the repo root would still try to exec a non-existent ${REPO_ROOT}/gradlew.
ANDROID_DIR="${REPO_ROOT}/android"
if [[ ! -x "${ANDROID_DIR}/gradlew" ]]; then
  echo "ERROR: ${ANDROID_DIR}/gradlew not found or not executable." >&2
  echo "       Run 'flutter pub get' (or a 'flutter build') first to generate it." >&2
  exit 2
fi

# Resolve one fdroid runtime classpath via `app:dependencies` (run from android/,
# where ./gradlew lives). `--console=plain` keeps the output greppable.
# NB: do NOT pass `-q`/`--quiet` here — Gradle's `--quiet` can suppress the very
# dependency tree we grep, which would silently produce a false "OK". The extra
# lifecycle noise never matches the GMS coordinate pattern.
#
# We prefer the RELEASE classpath (fdroidReleaseRuntimeClasspath) — that is what
# the shipped F-Droid APK resolves. But resolving the release classpath can fail
# in keyless environments (the #48 signing guard throws on a release context
# without a keystore). The GMS/MLKit exclude is FLAVOR-scoped (it applies to
# fdroidImplementation + every fdroid*RuntimeClasspath), so the DEBUG classpath
# proves the exact same thing. Fall back to it when release resolution fails.
run_app_dependencies() { # $1 = configuration name
  (cd "${ANDROID_DIR}" && ./gradlew --console=plain \
    app:dependencies --configuration "$1") 2>&1
}

GRAPH_CONFIG="fdroidReleaseRuntimeClasspath"
if ! GRAPH_OUT="$(run_app_dependencies "${GRAPH_CONFIG}")"; then
  echo "NOTE: could not resolve ${GRAPH_CONFIG} (likely the #48 keyless-release" >&2
  echo "      guard); falling back to fdroidDebugRuntimeClasspath — the exclude" >&2
  echo "      is flavor-scoped, so the debug classpath proves it too." >&2
  GRAPH_CONFIG="fdroidDebugRuntimeClasspath"
  if ! GRAPH_OUT="$(run_app_dependencies "${GRAPH_CONFIG}")"; then
    echo "ERROR: gradle dependency resolution failed for both the release and" >&2
    echo "       debug fdroid runtime classpaths:" >&2
    echo "${GRAPH_OUT}" >&2
    exit 2
  fi
fi

if echo "${GRAPH_OUT}" | grep -Eq "${GMS_GRAPH_PATTERN}"; then
  echo "FAIL: GMS/MLKit/Play-Core/Sentry coordinates present on ${GRAPH_CONFIG}:" >&2
  echo "${GRAPH_OUT}" | grep -E "${GMS_GRAPH_PATTERN}" >&2
  echo "HINT: run 'dart run tool/apply_fdroid_overrides.dart' first — the" >&2
  echo "      libre stubs (epic #3473) must be applied before resolving." >&2
  FAILED=1
else
  echo "OK: no com.google.android.gms / com.google.mlkit / com.google.android.play / io.sentry on ${GRAPH_CONFIG}."
fi

if [[ -n "${APK_PATH}" ]]; then
  echo "==> [B] dex bytecode audit — ${APK_PATH}"
  # WHAT THIS LAYER ASSERTS (#2584, #3069):
  #   The fdroid APK must ship NO proprietary Google code — i.e. no
  #   `com.google.android.gms.*` / `com.google.mlkit.*` / `com.google.android.play.*`
  #   class is DEFINED in the dex. We detect that with dexdump's
  #   `Class descriptor : 'L…;'` lines.
  #
  # WHY A DANGLING *REFERENCE* FAILS ONLY IN STRICT MODE (#3480):
  #   Since epic #3473 the libre build swaps every GMS/ML Kit/Play-Core/Sentry-
  #   pulling plugin for a Dart-only stub at the pub graph level, so a RELEASE
  #   fdroid dex carries ZERO references — F-Droid's `check apk` scanner
  #   enforces exactly that, and layer C mirrors it (strict mode, auto-enabled
  #   for release-named APKs). A DEBUG APK still legitimately retains inert
  #   references: R8 is off, so Flutter's own engine embedding keeps its dead
  #   PlayStoreDeferredComponentManager constant-pool entries (#3479 strips
  #   them only in release via the proguard keep-rule tuning). On debug the
  #   authoritative criterion therefore stays "no class DEFINITION", with the
  #   reference count printed for visibility.
  if [[ ! -f "${APK_PATH}" ]]; then
    echo "ERROR: APK not found: ${APK_PATH}" >&2
    exit 2
  fi

  WORK_DIR="$(mktemp -d)"
  trap 'rm -rf "${WORK_DIR}"' EXIT
  unzip -q -o "${APK_PATH}" 'classes*.dex' -d "${WORK_DIR}" || {
    echo "ERROR: failed to extract classes*.dex from APK." >&2
    exit 2
  }

  # Locate dexdump (Android build-tools). Optional — fall back to `strings`.
  # The build-tools lookup must be glob-safe: `${SDK_ROOT}/build-tools/*/dexdump`
  # can expand to NOTHING (no SDK, or a build-tools dir with no dexdump), so we
  # enumerate with `ls` + version-sort + an explicit `-x` test rather than a raw
  # glob that would silently leave a literal unexpanded path behind.
  DEXDUMP_BIN=""
  if command -v dexdump >/dev/null 2>&1; then
    DEXDUMP_BIN="$(command -v dexdump)"
  else
    SDK_ROOT="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
    if [[ -n "${SDK_ROOT}" && -d "${SDK_ROOT}/build-tools" ]]; then
      # newest build-tools first; take the first one that actually has dexdump.
      while IFS= read -r ver; do
        [[ -n "${ver}" ]] || continue
        if [[ -x "${SDK_ROOT}/build-tools/${ver}/dexdump" ]]; then
          DEXDUMP_BIN="${SDK_ROOT}/build-tools/${ver}/dexdump"
          break
        fi
      done < <(ls -1 "${SDK_ROOT}/build-tools" 2>/dev/null | sort -Vr)
    fi
  fi

  # `strings` may be absent on a minimal runner; `grep -a` on the binary dex is
  # an equivalent last-resort (the type descriptors are stored as plain ASCII).
  STRINGS_BIN=""
  command -v strings >/dev/null 2>&1 && STRINGS_BIN="$(command -v strings)"

  # IMPORTANT — SIGPIPE / pipefail safety (the bug that masked #2584):
  #   `dexdump "$dex" | grep -Eq PATTERN` is FATAL here. `grep -q` exits at the
  #   first match and closes the pipe; dexdump then dies with SIGPIPE (exit 141);
  #   under `set -o pipefail` the pipeline's status is dexdump's 141, so an `if`
  #   takes the ELSE branch on a DIRTY dex — a silent false "clean". (Reproduced
  #   on macOS bash 3.2.) We therefore NEVER `grep -q` a dexdump pipe: we capture
  #   the full match set into a variable with a `|| true` guard, then test it.
  DEX_DEF_HIT=0      # GMS/ML Kit class DEFINITIONS (proprietary code shipped) — FATAL
  DEX_REF_TOTAL=0    # dangling type REFERENCES (informational only)
  DEX_COUNT=0
  shopt -s nullglob
  for dex in "${WORK_DIR}"/classes*.dex; do
    DEX_COUNT=$((DEX_COUNT + 1))
    if [[ -n "${DEXDUMP_BIN}" ]]; then
      DUMP="$("${DEXDUMP_BIN}" -d "${dex}" 2>/dev/null || true)"
      # (a) class DEFINITIONS — the authoritative failure condition.
      DEFS="$(printf '%s\n' "${DUMP}" | { grep -E "${GMS_DEX_DEF_PATTERN}" || true; } | sort -u)"
      if [[ -n "${DEFS}" ]]; then
        echo "FAIL: GMS/ML Kit class DEFINITIONS in $(basename "${dex}") — proprietary code shipped:" >&2
        # `head` closes the pipe early; under pipefail that would surface a
        # spurious SIGPIPE from printf, so cap with sed (consumes all input).
        printf '%s\n' "${DEFS}" | sed -n '1,40p' >&2
        DEX_DEF_HIT=1
      fi
      # (b) dangling references — informational on a debug APK; FATAL in the
      # #3480 strict mode (layer C — the F-Droid `check apk` bar).
      REFS="$(printf '%s\n' "${DUMP}" | { grep -Eo "${GMS_DEX_PATTERN}[A-Za-z0-9/_$]+;" || true; } | sort -u)"
      if [[ -n "${REFS}" ]]; then
        DEX_REF_TOTAL=$((DEX_REF_TOTAL + $(printf '%s\n' "${REFS}" | grep -c .)))
        if [[ "${STRICT_REFS}" -eq 1 ]]; then
          echo "FAIL [strict]: dangling GMS/ML Kit/Play-Core/Sentry type REFERENCES in $(basename "${dex}") — F-Droid's check-apk scanner rejects these (#3480):" >&2
          printf '%s\n' "${REFS}" | sed -n '1,40p' >&2
          DEX_DEF_HIT=1
        fi
      fi
    else
      # No dexdump: ASCII type descriptors live in the dex as plain strings, but
      # `strings`/`grep -a` CANNOT distinguish a definition from a reference. We
      # fall back to the conservative reference scan and FAIL on any hit (the only
      # safe choice without dexdump); CI's ubuntu-latest always has dexdump, so
      # this branch is the local-without-SDK degradation only.
      if [[ -n "${STRINGS_BIN}" ]]; then
        SCAN_OUT="$("${STRINGS_BIN}" -a "${dex}" | { grep -E "${GMS_DEX_PATTERN}" || true; } | sort -u | head -40)"
      else
        SCAN_OUT="$({ grep -a -E "${GMS_DEX_PATTERN}" "${dex}" || true; } | sort -u | head -40)"
      fi
      if [[ -n "${SCAN_OUT}" ]]; then
        echo "FAIL: GMS/ML Kit/Play-Core type strings in $(basename "${dex}") (no dexdump — can't tell def from ref, failing conservatively):" >&2
        echo "${SCAN_OUT}" >&2
        DEX_DEF_HIT=1
      fi
    fi
  done
  shopt -u nullglob

  if [[ "${DEX_COUNT}" -eq 0 ]]; then
    echo "ERROR: no classes*.dex extracted from ${APK_PATH} — cannot run the dex audit." >&2
    exit 2
  fi
  if [[ -z "${DEXDUMP_BIN}" ]]; then
    echo "NOTE: dexdump not found — used the conservative 'strings' reference scan"
    echo "      (set ANDROID_HOME for the precise class-definition audit)."
  elif [[ "${STRICT_REFS}" -eq 1 ]]; then
    echo "INFO [strict]: ${DEX_REF_TOTAL} dangling GMS/ML Kit/Play-Core/Sentry type reference(s) — must be 0 (#3480)."
  else
    echo "INFO: ${DEX_REF_TOTAL} dangling GMS/ML Kit/Play-Core/Sentry type reference(s) to absent classes (inert on a debug APK; the release audit fails on any)."
  fi
  if [[ "${DEX_DEF_HIT}" -eq 0 ]]; then
    if [[ "${STRICT_REFS}" -eq 1 ]]; then
      echo "OK [strict]: zero GMS/ML Kit/Play-Core/Sentry definitions AND references in any dex."
    else
      echo "OK: no GMS/ML Kit/Play-Core/Sentry class DEFINITIONS in any dex — no proprietary Google code shipped."
    fi
  else
    FAILED=1
  fi
fi

if [[ "${FAILED}" -ne 0 ]]; then
  echo "==> AUDIT FAILED: the fdroid flavor ships GMS/ML Kit/Play-Core/Sentry" >&2
  echo "    code (coordinate on the runtime classpath, a proprietary class" >&2
  echo "    defined in the dex, or — in strict release mode — any dangling" >&2
  echo "    type reference, the F-Droid check-apk bar, #3480)." >&2
  exit 1
fi

echo "==> AUDIT PASSED: fdroid flavor ships no GMS/ML Kit/Play-Core/Sentry"
echo "    coordinates and no proprietary class definitions"
if [[ -n "${APK_PATH}" && "${STRICT_REFS}" -eq 1 ]]; then
  echo "    — and zero dangling type references (strict release bar, #3480)."
fi
exit 0
