#!/usr/bin/env bash
# License audit script for CI — ensures all dependencies use MIT-compatible licenses.
# Allowed: MIT, BSD-2-Clause, BSD-3-Clause, Apache-2.0, Unlicense, ISC, Zlib, BlueOak-1.0.0
# Forbidden: GPL, AGPL, LGPL, SSPL, EUPL, CC-BY-SA, CC-BY-NC
#
# Usage: bash scripts/license_audit.sh [--report]
#   --report  Generate docs/DEPENDENCY_LICENSES.md inventory

set -euo pipefail

REPORT_MODE=false
if [[ "${1:-}" == "--report" ]]; then
  REPORT_MODE=true
fi

# Allowed license patterns (case-insensitive grep)
ALLOWED_PATTERNS=(
  "MIT License"
  "MIT license"
  "Permission is hereby granted, free of charge"
  "BSD 2-Clause"
  "BSD-2-Clause"
  "Redistribution and use in source and binary forms"
  "BSD 3-Clause"
  "BSD-3-Clause"
  "Apache License"
  "Apache-2.0"
  "Licensed under the Apache License, Version 2.0"
  "The Unlicense"
  "This is free and unencumbered software"
  "ISC License"
  "ISC license"
  "Permission to use, copy, modify"
  "zlib License"
  "Zlib license"
  "BlueOak"
)

# Forbidden license patterns (case-insensitive grep)
FORBIDDEN_PATTERNS=(
  "GNU General Public License"
  "GNU GENERAL PUBLIC LICENSE"
  "GPL-2"
  "GPL-3"
  "AGPL"
  "GNU Affero"
  "LGPL"
  "GNU Lesser"
  "Server Side Public License"
  "SSPL"
  "European Union Public"
  "EUPL"
  "Creative Commons Attribution-ShareAlike"
  "CC-BY-SA"
  "Creative Commons Attribution-NonCommercial"
  "CC-BY-NC"
)

FORBIDDEN_DEPS=""
UNKNOWN_DEPS=""
REPORT_LINES=""
EXIT_CODE=0

# Get all non-dev dependencies (skip first line which is the project name)
DEPS=$(dart pub deps --no-dev --style=compact 2>/dev/null | tail -n +2 | sed 's/ .*//' | sort -u)

for pkg in $DEPS; do
  # Find the package's LICENSE file in the pub cache
  LICENSE_FILE=$(find ~/.pub-cache/hosted/pub.dev/"${pkg}-"* -maxdepth 1 -iname "LICENSE*" 2>/dev/null | head -1)

  if [ -z "$LICENSE_FILE" ]; then
    # Try hosted subdirectories
    LICENSE_FILE=$(find ~/.pub-cache/hosted/pub.dev/"${pkg}"* -maxdepth 2 -iname "LICENSE*" 2>/dev/null | head -1)
  fi

  LICENSE_TYPE="unknown"

  if [ -n "$LICENSE_FILE" ]; then
    # Check forbidden first
    IS_FORBIDDEN=false
    for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
      if grep -qi "$pattern" "$LICENSE_FILE" 2>/dev/null; then
        IS_FORBIDDEN=true
        LICENSE_TYPE="FORBIDDEN"
        break
      fi
    done

    if [ "$IS_FORBIDDEN" = true ]; then
      FORBIDDEN_DEPS="${FORBIDDEN_DEPS}\n  - ${pkg}"
    else
      # Check allowed
      IS_ALLOWED=false
      for pattern in "${ALLOWED_PATTERNS[@]}"; do
        if grep -qi "$pattern" "$LICENSE_FILE" 2>/dev/null; then
          IS_ALLOWED=true
          # Determine specific license type for report
          if grep -qi "Apache" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="Apache-2.0"
          elif grep -qi "BSD-3\|BSD 3" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="BSD-3-Clause"
          elif grep -qi "BSD-2\|BSD 2" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="BSD-2-Clause"
          elif grep -qi "Redistribution and use" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="BSD"
          elif grep -qi "MIT\|Permission is hereby granted, free of charge" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="MIT"
          elif grep -qi "ISC" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="ISC"
          elif grep -qi "Unlicense\|unencumbered" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="Unlicense"
          elif grep -qi "zlib" "$LICENSE_FILE" 2>/dev/null; then
            LICENSE_TYPE="Zlib"
          else
            LICENSE_TYPE="Allowed"
          fi
          break
        fi
      done

      if [ "$IS_ALLOWED" = false ]; then
        UNKNOWN_DEPS="${UNKNOWN_DEPS}\n  - ${pkg}"
        LICENSE_TYPE="UNKNOWN"
      fi
    fi
  else
    # Flutter SDK packages (like sky_engine) don't have separate LICENSE files
    # They are covered by the Flutter SDK license (BSD-3-Clause)
    LICENSE_TYPE="Flutter SDK (BSD-3-Clause)"
  fi

  REPORT_LINES="${REPORT_LINES}| ${pkg} | ${LICENSE_TYPE} |\n"
done

# Generate report if requested
if [ "$REPORT_MODE" = true ]; then
  mkdir -p docs
  {
    echo "# Dependency Licenses"
    echo ""
    echo "Auto-generated by \`scripts/license_audit.sh --report\`."
    echo ""
    echo "| Package | License |"
    echo "|---------|---------|"
    echo -e "$REPORT_LINES"
  } > docs/DEPENDENCY_LICENSES.md
  echo "License report written to docs/DEPENDENCY_LICENSES.md"
fi

# Report results
if [ -n "$FORBIDDEN_DEPS" ]; then
  echo "::error::GPL/AGPL/LGPL-licensed dependencies found:$(echo -e "$FORBIDDEN_DEPS")"
  echo "All dependencies must be MIT/BSD/Apache compatible (MIT project)."
  EXIT_CODE=1
fi

if [ -n "$UNKNOWN_DEPS" ]; then
  echo "::warning::Dependencies with unrecognized licenses:$(echo -e "$UNKNOWN_DEPS")"
  echo "Please verify these manually and add their license patterns to the audit script."
  # Unknown licenses are a warning, not a failure — manual review needed
fi

if [ $EXIT_CODE -eq 0 ]; then
  TOTAL=$(echo "$DEPS" | wc -w)
  echo "License audit passed — $TOTAL dependencies checked, all MIT/BSD/Apache compatible."
fi

exit $EXIT_CODE
