#!/usr/bin/env bash
# License audit script for CI -- ensures all dependencies use MIT-compatible licenses.
# Allowed: MIT, BSD-2/3, Apache-2.0, MPL-2.0, Unlicense, ISC, Zlib, BlueOak-1.0.0
# Forbidden: GPL, AGPL, LGPL, SSPL, EUPL, CC-BY-SA, CC-BY-NC
#
# Usage: bash scripts/license_audit.sh [--report]
#   --report  Generate docs/DEPENDENCY_LICENSES.md inventory

set -uo pipefail

REPORT_MODE=false
if [[ "${1:-}" == "--report" ]]; then
  REPORT_MODE=true
fi

FORBIDDEN_DEPS=""
UNKNOWN_DEPS=""
REPORT_LINES=""
EXIT_CODE=0

# Determine pub cache location
PUB_CACHE="${PUB_CACHE:-$HOME/.pub-cache}"

# Get all non-dev dependencies: parse lines starting with "- " from compact output
DEPS=$(dart pub deps --no-dev --style=compact 2>/dev/null | grep '^- ' | sed 's/^- //' | sed 's/ .*//' | sort -u || true)

if [ -z "$DEPS" ]; then
  echo "::warning::Could not parse dependencies from dart pub deps"
  echo "License audit skipped."
  exit 0
fi

echo "Checking licenses for dependencies..."

# classify_license FILE -> sets LICENSE_TYPE
# Strategy: check allowed licenses first (to handle MPL-2.0 which mentions GPL),
# then check forbidden only if no allowed match was found.
classify_license() {
  local file="$1"
  LICENSE_TYPE="UNKNOWN"

  # 1. Check for specific allowed licenses (order matters: specific before generic)
  if grep -qi "Mozilla Public License" "$file" 2>/dev/null; then
    LICENSE_TYPE="MPL-2.0"
    return
  fi
  if grep -qi "Apache License\|Apache-2.0\|Licensed under the Apache License" "$file" 2>/dev/null; then
    LICENSE_TYPE="Apache-2.0"
    return
  fi
  if grep -qi "BSD-3-Clause\|BSD 3-Clause" "$file" 2>/dev/null; then
    LICENSE_TYPE="BSD-3-Clause"
    return
  fi
  if grep -qi "BSD-2-Clause\|BSD 2-Clause" "$file" 2>/dev/null; then
    LICENSE_TYPE="BSD-2-Clause"
    return
  fi
  if grep -qi "Redistribution and use in source and binary forms" "$file" 2>/dev/null; then
    LICENSE_TYPE="BSD"
    return
  fi
  if grep -qi "Permission is hereby granted, free of charge" "$file" 2>/dev/null; then
    LICENSE_TYPE="MIT"
    return
  fi
  if grep -qi "MIT License\|MIT license" "$file" 2>/dev/null; then
    LICENSE_TYPE="MIT"
    return
  fi
  if grep -qi "ISC License\|ISC license" "$file" 2>/dev/null; then
    LICENSE_TYPE="ISC"
    return
  fi
  if grep -qi "Permission to use, copy, modify" "$file" 2>/dev/null; then
    LICENSE_TYPE="ISC"
    return
  fi
  if grep -qi "The Unlicense\|This is free and unencumbered software" "$file" 2>/dev/null; then
    LICENSE_TYPE="Unlicense"
    return
  fi
  if grep -qi "zlib License\|Zlib license" "$file" 2>/dev/null; then
    LICENSE_TYPE="Zlib"
    return
  fi
  if grep -qi "BlueOak" "$file" 2>/dev/null; then
    LICENSE_TYPE="BlueOak-1.0.0"
    return
  fi

  # 2. No allowed license matched -- check for forbidden licenses
  local forbidden_patterns=(
    "GNU General Public License"
    "GNU GENERAL PUBLIC LICENSE"
    "GPL-2"
    "GPL-3"
    "GNU Affero"
    "Server Side Public License"
    "SSPL"
    "European Union Public"
    "EUPL"
    "Creative Commons Attribution-ShareAlike"
    "CC-BY-SA"
    "Creative Commons Attribution-NonCommercial"
    "CC-BY-NC"
  )
  for pattern in "${forbidden_patterns[@]}"; do
    if grep -qi "$pattern" "$file" 2>/dev/null; then
      LICENSE_TYPE="FORBIDDEN"
      return
    fi
  done

  # 3. Neither allowed nor forbidden -- unknown
  LICENSE_TYPE="UNKNOWN"
}

for pkg in $DEPS; do
  # Find the package's LICENSE file in the pub cache
  LICENSE_FILE=""
  # shellcheck disable=SC2086
  for candidate in "$PUB_CACHE"/hosted/pub.dev/${pkg}-*/LICENSE* "$PUB_CACHE"/hosted/pub.dev/${pkg}-*/license*; do
    if [ -f "$candidate" ]; then
      LICENSE_FILE="$candidate"
      break
    fi
  done

  if [ -n "$LICENSE_FILE" ]; then
    classify_license "$LICENSE_FILE"

    if [ "$LICENSE_TYPE" = "FORBIDDEN" ]; then
      FORBIDDEN_DEPS="${FORBIDDEN_DEPS}\n  - ${pkg}"
    elif [ "$LICENSE_TYPE" = "UNKNOWN" ]; then
      UNKNOWN_DEPS="${UNKNOWN_DEPS}\n  - ${pkg}"
    fi
  else
    # Flutter SDK packages (like sky_engine, flutter) don't have separate LICENSE files
    # They are covered by the Flutter SDK license (BSD-3-Clause)
    LICENSE_TYPE="Flutter SDK (BSD-3-Clause)"
  fi

  REPORT_LINES="${REPORT_LINES}| ${pkg} | ${LICENSE_TYPE} |\n"
done

# Generate report if requested
if [ "$REPORT_MODE" = true ]; then
  mkdir -p docs
  {
    echo "# Dependency Licenses"
    echo ""
    echo "Auto-generated by \`scripts/license_audit.sh --report\`."
    echo ""
    echo "| Package | License |"
    echo "|---------|---------|"
    echo -e "$REPORT_LINES"
  } > docs/DEPENDENCY_LICENSES.md
  echo "License report written to docs/DEPENDENCY_LICENSES.md"
fi

# Report results
if [ -n "$FORBIDDEN_DEPS" ]; then
  echo "::error::GPL/AGPL/LGPL-licensed dependencies found:$(echo -e "$FORBIDDEN_DEPS")"
  echo "All dependencies must be MIT/BSD/Apache compatible (MIT project)."
  EXIT_CODE=1
fi

if [ -n "$UNKNOWN_DEPS" ]; then
  echo "::warning::Dependencies with unrecognized licenses:$(echo -e "$UNKNOWN_DEPS")"
  echo "Please verify these manually and add their license patterns to the audit script."
  # Unknown licenses are a warning, not a failure -- manual review needed
fi

if [ $EXIT_CODE -eq 0 ]; then
  TOTAL=$(echo "$DEPS" | wc -l)
  echo "License audit passed -- $TOTAL dependencies checked, all MIT/BSD/Apache/MPL compatible."
fi

exit $EXIT_CODE
